apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus.name" . }}-k8s-rules
  namespace: {{ .Release.Namespace }}
  labels:
    role: prometheus-rulefiles
    prometheus: k8s
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
data:
{{ toYaml .Values.prometheus.configmap.data | indent 2}}
