apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-kube-system-k8s
  namespace: kube-system
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-default-k8s
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-k8s
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus.name" . }}-k8s
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-kube-system-k8s
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus.name" . }}-kube-system-k8s
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-default-k8s
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus.name" . }}-default-k8s
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus.name" . }}-k8s
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
 
{{- if .Values.prometheus.alertmanager.shouldRbacCreate }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ .Release.Namespace }}-prometheus-rolebinding
  namespace: {{ .Values.prometheus.alertmanager.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-prometheus-role
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus.name" . }}-k8s
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ .Release.Namespace }}-prometheus-role
  namespace: {{ .Values.prometheus.alertmanager.namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
{{- end }}
