apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: {{ .Values.prometheus.service.prometheusLabel }}
    expose: "{{ .Values.prometheus.service.expose }}"
{{ include "prometheus.labels.stakater" . | indent 4 }}
{{ include "prometheus.labels.chart" . | indent 4 }}
  name: {{ template "prometheus.name" . }}-prometheus-k8s
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: "{{ .Values.prometheus.service.forceSslRedirect }}"
      kubernetes.io/ingress.class: {{ .Values.prometheus.service.ingressClass }}
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: {{ .Values.prometheus.service.prometheusLabel }}
    app: prometheus
