apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "name" . }}
  labels:
    k8s-app: {{ template "name" . }}
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  selector:
    matchLabels:
      prometheus: k8s
  namespaceSelector:
    matchNames:
    {{- range .Values.prometheus.smPrometheus.namespaceSelector }}
    - {{ . }}
    {{- end }}
  endpoints:
  - port: web
    interval: {{ .Values.prometheus.smPrometheus.interval }}
