apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  namespaceSelector:
    matchNames:
    {{- range .Values.prometheus.smNodeKubeStateMetrics.namespaceSelector }}
    - {{ . }}
    {{- end }}
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
