apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
