apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
    {{- range .Values.prometheus.smNodeExporter.namespaceSelector }}
    - {{ . }}
    {{- end }}
  endpoints:
  - port: http-metrics
    interval: {{ .Values.prometheus.smNodeExporter.interval }}
