apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  namespaceSelector:
    matchNames:
    {{- range .Values.prometheus.smPrometheus.namespaceSelector }}
    - {{ . }}
    {{- end }}
  endpoints:
  - port: web
    interval: 30s
